# Generated by Django 6.0 on 2025-12-05 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('type', models.CharField(choices=[('movie', 'Película'), ('series', 'Serie')], max_length=10)),
                ('popularity', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('poster_url', models.URLField(blank=True)),
                ('regions', models.CharField(default='AR', max_length=200)),
                ('genres', models.ManyToManyField(blank=True, to='catalog.genre')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='catalog.platform')),
            ],
        ),
    ]
